version: '2.1'
services:
  amule:
    image: ngosang/amule
    container_name: amule
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - GUI_PWD=${GUI_PWD}
      - WEBUI_PWD=${WEBUI_PWD}
      - MOD_AUTO_RESTART_ENABLED=${MOD_AUTO_RESTART_ENABLED}
      - MOD_AUTO_RESTART_CRON=${MOD_AUTO_RESTART_CRON}
      - MOD_AUTO_SHARE_ENABLED=${MOD_AUTO_SHARE_ENABLED}
      - MOD_AUTO_SHARE_DIRECTORIES=${MOD_AUTO_SHARE_DIRECTORIES}
      - MOD_FIX_KAD_GRAPH_ENABLED=${MOD_FIX_KAD_GRAPH_ENABLED}
    ports:
      - "4711:4711" # web ui
      - "4712:4712" # remote gui, webserver, cmd ...
      - "4662:4662" # ed2k tcp
      - "4665:4665/udp" # ed2k global search udp (tcp port +3)
      - "4672:4672/udp" # ed2k udp
    volumes:
      - ${AMULE_CONFIG_PATH}:/home/amule/.aMule
      - ${AMULE_DOWNLOAD_PATH}:/incoming
      - ${AMULE_INCOMPLETE_PATH}:/temp
    restart: unless-stopped
