services:
  amule:
    image: ngosang/amule
    container_name: amule
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - GUI_PWD=${GUI_PWD}
      - WEBUI_PWD=${WEBUI_PWD}
      - MOD_AUTO_RESTART_ENABLED=${MOD_AUTO_RESTART_ENABLED}
      - MOD_AUTO_RESTART_CRON=${MOD_AUTO_RESTART_CRON}
      - MOD_AUTO_SHARE_ENABLED=${MOD_AUTO_SHARE_ENABLED}
      - MOD_AUTO_SHARE_DIRECTORIES=${MOD_AUTO_SHARE_DIRECTORIES}
      - MOD_FIX_KAD_GRAPH_ENABLED=${MOD_FIX_KAD_GRAPH_ENABLED}
      - MOD_FIX_KAD_BOOTSTRAP_ENABLED=${MOD_FIX_KAD_BOOTSTRAP_ENABLED}
    ports:
      - "${AMULE_WEBUI_PORT}:4711" # web ui
      - "${AMULE_REMOTE_GUI_PORT}:4712" # remote gui, webserver, cmd ...
      - "${AMULE_ED2K_TCP_PORT}:4662" # ed2k tcp
      - "${AMULE_ED2K_SEARCH_UDP_PORT}:4665/udp" # ed2k global search udp (tcp port +3)
      - "${AMULE_ED2K_UDP_PORT}:4672/udp" # ed2k udp
    volumes:
      - ${AMULE_CONFIG_PATH}:/home/amule/.aMule
      - ${AMULE_DOWNLOAD_PATH}:/incoming
      - ${AMULE_INCOMPLETE_PATH}:/temp
    restart: unless-stopped
